### ISSUE TITLE
Exporter fails when vhName contains the port

### ISSUE THREAD

**Issue by AndreyBayev** [myokoo/litespeed_exporter#6]
Exporter fails if virtualHostLine looks like below:

`REQ_RATE [APVH_domain.com:81]: REQ_PROCESSING: 1, REQ_PER_SEC: 0.1, TOT_REQS: 6, PUB_CACHE_HITS_PER_SEC: 0.0, TOTAL_PUB_CACHE_HITS: 0, PRIVATE_CACHE_HITS_PER_SEC: 0.0, TOTAL_PRIVATE_CACHE_HITS: 0, STATIC_HITS_PER_SEC: 0.1, TOTAL_STATIC_HITS: 6`

The solution is to modify lines 100 and 101 in litespeed_exporter/pkg/rtreport/parse.go:

`        i := strings.Index(lineText, ":")`
`        report.VirtualHostReport[vhName], report.error = convertStringToMap(lineText[i+1:])`

to:

`        i := strings.Index(lineText, "]:")`
`       report.VirtualHostReport[vhName], report.error = convertStringToMap(lineText[i+2:])`

**Comment by myokoo** [comment]
Thank you for your report and commit!!
I've merged them.
